{% set name = "silvimetric" %}
{% set version = "1.3.1" %}
{% set sha256 = "a7daf5cb8eb617642829cc9086d4aa07a3705589fbf55a8e0f58d701e9c494be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/silvimetric-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0
  entry_points:
    - silvimetric = silvimetric.cli.cli:cli

requirements:
  host:
    - python  >3.8
    - pip
    - setuptools
  run:
    - python  >3.8
    - click
    - dask
    - pyproj
    - gdal
    - python-pdal
    - pandas
    - tiledb-py
    - scipy
    - dill
    - typing_extensions
    - lmoments3

test:
  commands:
    - python -c "import silvimetric"
    - silvimetric --help

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for extracting LiDAR forestry metrics
  doc_url: https://silvimetric.com
  dev_url: https://github.com/hobuinc/silvimetric

extra:
  recipe-maintainers:
    - hobu
