{% set name = "silvimetric" %}
{% set version = "1.2.2" %}
{% set sha256 = "57e05fa95f3d9ef742a97342868cb4f13ab1b7d5646de0d886d280e3bd6d088d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/silvimetric-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0
  entry_points:
    - silvimetric = silvimetric.cli.cli:cli

requirements:
  host:
    - python  >3.8
    - pip
    - setuptools
  run:
    - python  >3.8
    - click
    - dask
    - pyproj
    - gdal
    - python-pdal
    - pandas
    - tiledb-py
    - scipy
    - dill

test:
  commands:
    - python -c "import silvimetric"
    - silvimetric --help

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for extracting LiDAR forestry metrics
  doc_url: https://silvimetric.com
  dev_url: https://github.com/hobuinc/silvimetric

extra:
  recipe-maintainers:
    - hobu
